### ISSUE TITLE
'extractSerpent2GCs.py' does not work

### ISSUE THREAD

**Issue by robfairh** [arfc/moltres#102]
I am trying to follow the tutorial to create the XS for the moltres input and trying to reproduce the tutorial:
https://github.com/arfc/moltres/tree/devel/tutorial/step01_groupConstants

and this is the error I get:
```
Making properties for materials:
['fuel', 'moder']
Traceback (most recent call last):
  File "extract2.py", line 213, in <module>
    unimapFile, serp1=args.serp1, fromMain=True)
  File "extract2.py", line 77, in makePropertiesDir
    uniMap[currentMat]), 0, 0].gc[goodMap['BETA_EFF']]
KeyError: (2, 0, 0)
```

The issue can be closed when 'extractSerpent2GCs.py' works again for the example in the tutorial.

**Comment by smpark7** [comment]
I can't replicate this error. Do you have the latest version of Moltres? We made a PR last week to fix a bug in extractSerpent2GCs.py

**Comment by robfairh** [comment]
I know. And yes, I have the latest version.

**Comment by smpark7** [comment]
Did you run ```extractSerpent2GCs.py MSREProperties msre_gentry_4g tempMapping.txt secBranch.txt universeMapping.txt```? 
Also, it seems as though you renamed the python script to ```extract2.py```. Check whether it's the same as the latest file we have on the repo.

**Comment by robfairh** [comment]
```
roberto ~/projects/moltres/tutorial/step01_groupConstants (tutorial) $ ../../python/extractSerpent2GCs.py MSREProperties msre_gentry_4g tempMapping.txt secBranch.txt universeMapping.txt
Making properties for materials:
['fuel', 'moder']
Traceback (most recent call last):
  File "../../python/extractSerpent2GCs.py", line 213, in <module>
    unimapFile, serp1=args.serp1, fromMain=True)
  File "../../python/extractSerpent2GCs.py", line 77, in makePropertiesDir
    uniMap[currentMat]), 0, 0].gc[goodMap['BETA_EFF']]
KeyError: (2, 0, 0)
```

**Comment by smpark7** [comment]
It appears that serpent-tools made a change to accept non-integer IDs for universes. I haven't looked at it closely but I think the coe parsing function produces a dict with string keys for the universe ID. So for this case, instead of ```(2, 0, 0)```, it should be ```("2", 0, 0)```.

This should be a simple fix so you're welcome to make a PR to fix the script. Otherwise I'll try to make one sometime this week.
