### ISSUE TITLE
Fission spectra, CHIT vs CHIP vs CHID

### ISSUE THREAD

**Issue by smpark7** [arfc/moltres#108]
Serpent outputs the fission spectra data as ```INF_CHIT```, ```INF_CHIP```, and ```INF_CHID```, which are the total effective, prompt and delayed fission spectra.

Currently, the two common material kernels for Moltres, ```GenericMoltresMaterial``` and ```MoltresJsonMaterial```, import ```INF_CHIT``` and ```INF_CHID``` values from Serpent output data. They're imported and renamed into ```chi``` and ```chi_d``` respectively. ```chi``` is subsequently (erroneously) used in the ```CoupledFissionKernel``` as the prompt fission spectra value.

I believe this is wrong because ```INF_CHIT``` represents the total effective fission spectra. This error may have occurred due to the fact that older examples did not have CHIP and CHID as separate data entities.

@katyhuff If my analysis is correct, I'll go ahead and make the fixes (which should be pretty straightforward).

Edit: Maybe not so straightforward to maintain backward compatibility with old input files

**Comment by smpark7** [comment]
![image](https://user-images.githubusercontent.com/30237775/74195154-4051f980-4c20-11ea-9936-09eee6a9904d.png)

```CHI``` values here to show that the differences are significant.

**Comment by smpark7** [comment]
Also, I'm not sure about SCALE output format and whether it has the same issue.

**Comment by katyhuff** [comment]
The actual problem is not quite what you have described here. 
The correction is made, appropriately, if accounting for delayed neutrons with the approach:

$$\Chi_p = (1-\beta) \Chi_d$$

We do this in the if block related to _account_delayed.

As discussed in our meeting, though, we should probably do this individually for each group, though... That's a separate issue.

**Comment by smpark7** [comment]
It should be that <img src="https://render.githubusercontent.com/render/math?math=\chi^p_g \neq (1-\beta)\chi^t_g"> because the values I provided above show that for some groups, <img src="https://render.githubusercontent.com/render/math?math=\chi^p_g > \chi^t_g">, while <img src="https://render.githubusercontent.com/render/math?math=\chi^p_g < \chi^t_g"> for others. If the equality were true, \chi^p_g should always be smaller than \chi^t_g because (1-\beta) is always less than 1.

Instead, from the Stacey Nuclear Reactor Physics textbook (equation 16.20a) and Alex's paper, the fission source term for neutron group g should be

<img src="https://render.githubusercontent.com/render/math?math=\chi^p_g \sum^G_{g'} (1-\beta)\nu\Sigma^f_{g'} \phi_{g'}">

The current implementation of ```CoupledFissionKernel``` for neutron group g with ```_account_delayed = true``` is:

 <img src="https://render.githubusercontent.com/render/math?math=\chi^t_g \sum^G_{g'} (1-\beta)\nu\Sigma^f_{g'} \phi_{g'}">. 

The implementation differs from the standard formulation by the type of \chi terms used.

**Comment by gridley** [comment]
Hey @smpark7, I don't know if you ever fixed this, but I just had to do the math on this for another project and thought I'd share my result with you. You're definitely correct that the current approach is incorrect. If there is a separate delayed neutron emission spectrum for each delayed group, the relation should be

![image](https://user-images.githubusercontent.com/18088906/85600061-1e7b7100-b61b-11ea-8aa5-d198536edcec.png)

Where the subscript j indexes all the delayed neutron groups. This confirms what you're saying. Sorry that this was not put in correctly. I may have written that code... so, apologies!

**Comment by smpark7** [comment]
Hi @gridley, I have not implemented a fix for this but it should be a relatively simple task of swapping the CHI_T's for CHI_P's under a conditional that checks whether CHI_D data exists. I will self-assign this as a backlog task to be completed in the next week or so but feel free to make the changes if you want to jump in earlier.
