### ISSUE TITLE
Create a Style Guide

### ISSUE THREAD

**Issue by yardasol** [arfc/moltres#131]
EDIT 1: The first comment below specifies a new style guide is not necessary and linking to the MOOSE code standards should be sufficient. The title of this issue has been updated to reflect this.

The current CONTRIBUTING.md file's link to the MOOSE code standards is broken.

This issue can be closed when the CONTRIBUTING.md document links to the [correct MOOSE code standards page](https://www.mooseframework.org/framework_development/code_standards.html).

The original issue is preserved below
----------------------------------------
Original title: Create a Style Guide

Moltres does not have a Style Guide. A Style Guide defines the appropriate style for writing (code, documentation, etc.) for a project. A style guide is important for open source projects like Moltres to ensure that the project remain consistent in both code and documentation as new features are added and old ones updated/revised.

The Style Guide should specify

 - code structure
 - documentation practices
 - file structure
 

Some of these items already exist in the [current CONTRIBUTING.md document](https://github.com/arfc/moltres/blob/devel/CONTRIBUTING.md).

This list is not comprehensive and should be updated as necessary. The Style Guide should use clear, concise, and easy to read language (this sentence is an example of one you might find in a style guide). A good place to start for inspiration might be the [ARFC Guides](http://arfc.github.io/manual/guides/), the [OpenMC style guide](https://docs.openmc.org/en/latest/devguide/styleguide.html#), or the [MOOSE code standards](https://www.mooseframework.org/framework_development/code_standards.html)

This issue can be closed once a Style Guide that addresses the above items exists.

**Comment by katyhuff** [comment]
Moltres does and should follow the already existing MOOSE style guide. Please do not create a second style guide just for moltres. Please just link to the MOOSE one.

https://www.mooseframework.org/framework_development/code_standards.html

**Comment by yardasol** [comment]
Makes sense to me. Issue has been updated to reflect this.

**Comment by yardasol** [comment]
Hmm, now this seems to just duplicate #128. Going to close as duplicative.

**Comment by yardasol** [comment]
duplicative of #128
