### ISSUE TITLE
FissionHeatSource.C may be wrong

### ISSUE THREAD

**Issue by robfairh** [arfc/moltres#141]
At the moment the [FissionHeatSource](https://github.com/arfc/moltres/blob/devel/src/kernels/FissionHeatSource.C) calculates the following:

```
r += -_test[_i][_qp] * _fissxs[_qp][i] * (*_group_fluxes[i])[_qp] * _power / _tot_fissions;
```

*power* being the reactor power and *tot_fissions* is the integral of the fission rate in the reactor.

This is the formula:
<img src="https://render.githubusercontent.com/render/math?math=%5Cfrac%7B%5CSigma_f%5Cphi%7D%7B%5Cint%5CSigma_f%5Cphi%20dV%7D%20Power">

The heat source should actually include *Kappa* (energy/fission) and the postprocessor should be *tot_fission_heat*.
The only case when the use of the formula above is correct is when there is only one fuel region or all the fuel regions share the same value for *Kappa* which would cancel it out.

The residual should look like this:

```
    r += -_test[_i][_qp] * _fisse[_qp][i] * _fissxs[_qp][i] * (*_group_fluxes[i])[_qp] * _power / _tot_fission_heat;
```

And this is how the formula should be:

<img src="https://render.githubusercontent.com/render/math?math=%5Cfrac%7B%5CKappa%20%5CSigma_f%5Cphi%7D%7B%5Cint%20%5CKappa%20%5CSigma_f%5Cphi%20dV%7D%20Power">

This issue can be closed when:
- [x] someone has analyzed this issue.
- [ ] the implementations have been made.

**Comment by robfairh** [comment]
@smpark7 thoughts?

**Comment by smpark7** [comment]
@robfairh Hey yea I think you're right. I never noticed because all of the reactors I've dealt with so far only had regions that shared the same Kappa.

**Comment by smpark7** [comment]
The KAPPA values can differ between neutron energy groups too (by ~1MeV). So this is wrong even for a single fuel region reactor if you have > 1 energy group.

**Comment by robfairh** [comment]
Oh yeah, you are right.
I'll implement the changes and make a PR.
The changes in FissionHeatSource.C are straightforward, but there are several files that use it and the implementation will not be backward compatible.
Those files are part of the tests and some of the problems.
I will make the changes in the tests files, should I do it for the problem files as well?

**Comment by smpark7** [comment]
Seems like there's one test that uses it. The resulting flux should be almost the same since the group 1 and 2 FISSE only differ by 1e-4 MeV. The problem files have long been backward incompatible (#87) so don't worry about those.

**Comment by robfairh** [comment]
The Jacobian is also wrong. Here is the current Jacobian:
```
    jac += -_test[_i][_qp] * _d_fissxs_d_temp[_qp][i] * (*_group_fluxes[i])[_qp] * _power /
           _tot_fissions;
```

It is missing '_phi[_j][_qp]'.
The new Jacobian should look like this:

```
    jac += -_test[_i][_qp] * (_fisse[_qp][i] * _d_fissxs_d_temp[_qp][i] * _phi[_j][_qp] +
                              _d_fisse_d_temp[_qp][i] * _phi[_j][_qp] * _fissxs[_qp][i]) *
                              (*_group_fluxes[i])[_qp] * _power / _tot_fission_heat;
```

**Comment by robfairh** [comment]
[FissionHeatSourceAux](https://github.com/arfc/moltres/blob/devel/src/auxkernels/FissionHeatSourceAux.C) is also wrong. Same issue as FissionHeatSource.C
