### ISSUE TITLE
Update Doxygen documentation

### ISSUE THREAD

**Issue by smpark7** [arfc/moltres#146]
This issue can be closed when the Doxygen documentation in Moltres is updated to reflect the latest Moltres build.

The goal is to update the Doxygen generated html files for ```arfc.github.io/moltres```, which were last compiled in 2017, so that the latest kernels and other objects are accounted for.

This is separate from (but somewhat related to) issue #133, which highlights missing docstrings for functions and variables in .h files. Ideally, we would close #133 before closing this issue.

**Comment by smpark7** [comment]
@yardasol How's the progress with #133? I was thinking of just updating the Doxygen files first and then running another update after #133 is resolved

**Comment by yardasol** [comment]
@smpark7 I started a [list of files](https://github.com/yardasol/moltres/blob/docum/list_of_files_to_add_documentation.txt) back in October in order to determine which ones needed attention. Most of it is not currently filled out.

**Comment by yardasol** [comment]
@smpark7 Are you updating the existing doxygen files or are you adding new ones as well?

**Comment by smpark7** [comment]
Both. Doxygen updates existing files if there are any changes, and creates new ones for kernels/objects that didn't exist before. I'll go ahead and make a PR because a Doxygen update is long overdue. We can update it again whenever needed
