### ISSUE TITLE
Precursor loop heavy tests are failing with latest MOOSE build

### ISSUE THREAD

**Issue by smpark7** [arfc/moltres#152]
This issue can be closed when we fix the precursor loop heavy tests that are currently failing with the latest MOOSE build.

The latest MOOSE build introduces the new ```Reporter``` system and associated changes to ```MultiAppPostprocessorTransfer```. Unfortunately, these changes are causing the precursor loop heavy tests to fail. CIVET did not indicate these tests were failing because it only runs non-heavy tests from external apps for pull requests in MOOSE.

Moltres would benefit from a new non-heavy test for the precursor looping capability so that CIVET would alert us to failing precursor loop tests. One suggestion would be to implement the existing heavy test with a lesser number of timesteps.

**Comment by smpark7** [comment]
PSA: Before this issue is fixed, you can still compile and use Moltres using the current version of the moose submodule in this repo. For your conda environment, you need to install:
```
conda install moose-libmesh=2020.11.04 moose-tools=2020.04.13
```
because the latest conda moose environment is not compatible with the moose submodule on Moltres.

**Comment by robfairh** [comment]
@smpark7 What should we do about this? Should we update the submodule and also update the conda moose environment?

**Comment by smpark7** [comment]
No. Our pre_loop and pre_loop_ins tests will fail if we update the submodule. The error message from the failed tests is:
```
Compiling C++ (in opt mode) /opt/civet/build_1/moltres/unit/src/main.C...
/opt/civet/build_1/moltres/unit/src/main.C:3:10: fatal error: cppunit/XmlOutputter.h: No such file or directory
   3 | #include "cppunit/XmlOutputter.h"
     |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [/opt/civet/build_1/moltres/moose/framework/build.mk:119: /opt/civet/build_1/moltres/unit/src/main.x86_64-pc-linux-gnu.opt.lo] Error 1
make: *** Waiting for unfinished jobs....
ERROR: exiting with code 2
```
I mentioned the conda moose environment versions above because the latest conda moose environment versions are not compatible with the moose submodule version in devel. We have to figure out a fix for PrecursorAction.C in response to the new ```Reporter``` system and ```MultiAppPostprocessorTransfer```.

**Comment by smpark7** [comment]
Closed by https://github.com/idaholab/moose/pull/17485

ReporterData now checks for a reporter value after it is declared.
