### ISSUE TITLE
Update installation instructions in readme

### ISSUE THREAD

**Issue by smpark7** [arfc/moltres#154]
With moose [environment](https://mooseframework.inl.gov/getting_started/installation/conda.html) packages readily available on conda, the installation instructions in the top-level directory readme are out-of-date. There is no need to go through the extra hassle of building libmesh from the moose submodule since the moose conda environment provides it along with other prerequisite modules. Accordingly, the ```build_libmesh_and_moltres.sh``` script in the top-level directory is no longer required.

This issue can be closed when the instructions on the readme are updated as described above and ```build_libmesh_and_moltres.sh``` is deleted.

**Comment by gwenchee** [comment]
closed with #180
