### ISSUE TITLE
MSBR Diffusion Coefficient Generation

### ISSUE THREAD

**Issue by katyhuff** [arfc/moltres#16]
In addition to group constants, the diffusion coefficients for the array of temperatures must be generated. This issue can be closed when a reasonable method for generating (or approximating) these diffusion coefficients (perhaps with newt, perhaps with heuristics & serpent) has been achieved and these diffusion coefficients have been calculated for the MSBR.

**Comment by katyhuff** [comment]
@andrewryh  --- I think you've done this, right?

**Comment by andrewryh** [comment]
No, I didn't create SCALE model to generate it. So, it is in a backlog now

**Comment by katyhuff** [comment]
gotcha.

**Comment by katyhuff** [comment]
Should this be closed as wontfix? Alternatively, we could unassign it from you, and let someone else pick it up sometime.

**Comment by andrewryh** [comment]
Let's unassign it
