### ISSUE TITLE
Demonstrate DistributedMesh in Moltres

### ISSUE THREAD

**Issue by lindsayad** [arfc/moltres#18]
Will be essential for larger reactor simulations like MSBR

**Comment by katyhuff** [comment]
hi @lindsayad .... there may be an opportunity for @andrewryh to bring this closer to completion for an MSBR full core demonstration... he may need your guidance! :D

**Comment by lindsayad** [comment]
Glad to help when needed!

**Comment by katyhuff** [comment]
Should this be closed as finished or as wontfix? Alternatively, we could unassign it from @andrewryh , and let someone else pick it up sometime.

**Comment by andrewryh** [comment]
@katyhuff 
As far as I know, it is already a working feature, seamlessly for the user (libMesh do it). So, I guess it can be closed. But @lindsayad knows better

**Comment by lindsayad** [comment]
Yea this certainly isn’t a bug. Any MOOSe simulation can be run with distributed mesh these days. So yea I would probably close this as in issue. It’s more like “it would be cool if we ran a 10 million element mesh so that we need to use a distributed mesh” kind of thing :-)

**Comment by lindsayad** [comment]
Closing because MOOSE runs reliably with distributed mesh (indeed it is a test target that is run with every pull request into MOOSE)
