### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by abachma2** [arfc/moltres#187]
While looking through this repo I noticed a few things with the documentation:
[ ] The link to MOOSE wiki, tutorial, and examples are not working. I got a message that the links couldn't be found. 
[ ] The Moltres page on the ARFC website have Alex Lindsey listed for dev questions. Should he be removed (I can also raise this issue in that repo if this needs to be updated)?
[ ] The Doxygen pages are very blank when I click on the link, and it's not obvious where to go
[ ] I would consider changing the name of the `Nts` module (I think it's a module). It's not intuitive on what that means. 
[ ] Something should be added about ``tutorial/`` directory to either the README or the wiki. The wiki contains an example from the tests directory, which doesn't seem like an intuitive place to pull an example from. 
[ ] Add more description to the problems in ``tutorials/``. Some of them have decent descriptions in their README, but not all are clear. 
[ ] General pattern of more than 80 characters/line in the README's

**Comment by smpark7** [comment]
Thanks for reviewing the Moltres repo! I'll address issues 1-3 in a PR today and create separate issues for 4-6. About issue 7, we follow the 100 character limit instead of the 80 limit.

**Comment by smpark7** [comment]
I'm closing this issue because it has been either addressed by PRs #189 and #190, or expanded upon in issue #191.
