### ISSUE TITLE
Generate XSEC tables for moltres that are functions of control rods

### ISSUE THREAD

**Issue by lindsayad** [arfc/moltres#22]
Essential for transient scenarios. Need to determine whether we're using:

- [x] Serpent: Current drawback: How to handle diffusion coefficients
- [ ] Newt/Scale: Current drawback: How to handle control rod heights with 2D simulation?

**Comment by gridley** [comment]
This was added a while ago in the tutorials folder. moltres/tutorials/step01<tab> includes fuel.coe, which has GCUs from the freezing point of FLiBe all the way up to 2000K in ~100 K intervals, generated at 5 linearly spaced control rod positions between full withdrawal and full insertion. Full insertion for the MSRE, by the way, does not reach the bottom of the core. The rods only reach to about 23 cm above the bottom of the moderator region. The new Serpent model's integral rod worth for rod 1, 2, and 3 was found to have 12, 5, 4 percent error respectively compared to ORNL experiments. This may have to do with how the experiment channel was modeled. In reality, it was mostly void. Here it was approximated as pure graphite to keep isotropic diffusion most valid. I have the precise errors and worths written in a notebook at my dorm.
