### ISSUE TITLE
transatomic-like reactor

### ISSUE THREAD

**Issue by katyhuff** [arfc/moltres#23]
This issue can be closed when a Transatomic-like reactor design has been modeled with Moltres. Steady state and transient problems should both be demonstrated and verified.

i.e. http://www.transatomicpower.com/wp-content/uploads/2015/04/Neutronics-White-Paper-v1.1.pdf

**Comment by lindsayad** [comment]
Why was this closed? Has someone actually modeled a Transatomic-like reactor? If so, it hasn't been committed to the repo
