### ISSUE TITLE
Feature: MOOSE submodule auto updates

### ISSUE THREAD

**Issue by nglaser3** [arfc/moltres#282]
## Background and motivation
The MOOSE submodule for Moltres has become extremely out-dated. Now, when using a more up-to-date moose-dev / MOOSE version, Moltres's sa tests fail. See #281. To address this problem we are having to go through months of MOOSE updates to find specifically which one is causing problems. 

## Description of idea
Automate updating the MOOSE submodule. A possible method is with dependabot. The automation should create a PR, so that CIVET can do the testing to see whether the update works or not. If the update works, simply merge. If not, then we address the problems and then merge. 

## Implementation details
Add to github actions or create a dependabot.yml file to update MOOSE once a week, creating a PR to do so. This PR then relies on CIVET to do the actual testing. 

## Potential snags
- CIVET not triggering when PR is created
- Enabling Dependabot on the Moltres Repo

**Comment by smpark7** [comment]
Addressed by #283
