### ISSUE TITLE
Aqueous homogeneous reactor experiment benchmarking

### ISSUE THREAD

**Issue by gridley** [arfc/moltres#30]
Initial goals are to benchmark moltres on the MSRE. We forgot one thing by narrowing our view to molten salt: there is one more reactor to benchmark against. ORNL, in its glorious Weinberg days, built this bad boy:

![image](https://user-images.githubusercontent.com/18088906/27488686-88d64dba-57fd-11e7-980d-4aab8b549496.png)

I don't see any transient data for this, but maybe some of the ORNL people have data. Shoudn't be hard to model: Wigner called it "a pot, a pipe, and a pump". This could provide better evidence that moltres is reliably transporting DNPs.

https://info.ornl.gov/sites/publications/files/Pub20808.pdf

**Comment by katyhuff** [comment]
These various aqueous solutions (water + uranyl sulfites and similar) certainly have liquid fuel, and some of the transport will be analogous. The TH will be quite different though -- high pressure two phase flow rather than single phase...

**Comment by gridley** [comment]
Right, involving two-phase would

**Comment by gridley** [comment]
oops, didn't mean to hit that button. I was going to say: the physics here would probably be pretty interesting. Radiolysis of water may have some effect.
