### ISSUE TITLE
Need a logo with appropriate usage license. 

### ISSUE THREAD

**Issue by katyhuff** [arfc/moltres#4]
I know you like this image: https://yt3.ggpht.com/-m228mYexdB0/AAAAAAAAAAI/AAAAAAAAAAA/BUb24swAfxw/s900-c-k-no-mo-rj-c0xffffff/photo.jpg

But, I'm concerned it might be copyrighted or restricted use.
This issue can be closed, either:
- [ ] when the rights to this image have been found and comply with our needs (free reuse with modification)
- [ ] when a logo has been found (or made [perhaps with autodraw](https://www.autodraw.com/)) to which we have appropriate rights

**Comment by lindsayad** [comment]
Alright, I found a picture of a pheonix:

![phoenix_cc0](https://cloud.githubusercontent.com/assets/10248304/25443309/12bd1432-2a6d-11e7-8b1c-7c5286cfd93b.jpg)

which is CC0 licensed: https://pixabay.com/en/phoenix-bird-fire-sun-bright-red-500469/

**Comment by katyhuff** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/8508524-116454032_15-s1-v1.png?transparent=1&palette=1&width=246) 

I'll add it to the website.
