### ISSUE TITLE
Decay heat

### ISSUE THREAD

**Issue by gridley** [arfc/moltres#47]
Moltres shows great strength in its ability to run transients. In order to simulate more exciting transients, it seems that some kernel sort of like the gamma heating kernel could be used in order to approximate this. The kernel could take parameters calculated from power history as given in [this document.](https://lost-contact.mit.edu/afs/umich.edu/user/d/a/dafish/Favorites/alex%20harrington/user/t/j/tjtrahan/Public/CoursePack/CP-14%20ANS-5.1.PDF)

Implementing this, Moltres could be used to ensure that passive cooling ability works as expected in shutdown states.

**Comment by lindsayad** [comment]
Sounds good to me!

**Comment by gridley** [comment]
Just had a small realization on this: decay heat precursors will be producing around 7% of the heat even in steady-operation. This would skew power distribution further from the stationary fuel distribution. Coming up with heating values for each group, dividing the groups, and determining decay constants wouldn't be easy, but we may be able to deduce something for a one group decay heat precursor transport approach from something @andrewryh mentioned earlier today:

>  1.4 Mw of heat is generated in the fuel outside the nominal core volume

So, we may be able to approximate the decay constant, fission yield, and heating value given this information combined with other parameters like flow velocity and external loop volume. This could be the source of our error in the fast flux that the reviewer mentioned. Also, it could be skewing the peak temperature in the graphite away from the documented MSRE axial position.

**Comment by lindsayad** [comment]
Can you explain why it would increase the fast flux?

**Comment by gridley** [comment]
You'd get temperature distribution skewed to be hotter at the top. This makes the axial midplane colder than originally, thus shifting fission rate to be higher in the axial midplane, so you get higher fast flux. I suppose only the silicon will tell the truth, in the end. (although it may be late)
