### ISSUE TITLE
External salt loop only couples on timestep_begin

### ISSUE THREAD

**Issue by gridley** [arfc/moltres#70]
In PrecursorAction.C, the code which controls coupling to the external salt loop should be updated so that inlet and outlet connections between the reactor and salt loop get updated at time appropriate for each solve. In particular, the coupling currently only gets updated now at timestep_begin, since we typically run long adaptive timestep transients to obtain the steady state. A (the one) user outside UIUC (yay!) desires to run InversePowerIteration solves with the external salt loop, so some code to automatically switch postprocessor transfers from timestep_begin to nonlinear iterations should be added. It would go around line 381 of PrecursorAction.C. This is more of a TODO for me, unless someone else wants to get it.

**Comment by katyhuff** [comment]
Good luck!

**Comment by gridley** [comment]
Wait... we can just couple only on nonlinear steps. I'll check. Should be a one-word code fix...

**Comment by gridley** [comment]
PR #72 fixed this.
